kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup-pvc
  namespace: etcd-backup
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi
  storageClassName: netapp
  volumeMode: Filesystem
